### ISSUE TITLE
i kind of.. dont understand?

### ISSUE THREAD

**Issue by Domxoxo** [eKeiran/Cleartext-with-Album-Art#5]
i just dont get it, i did all the steps, but now im stuck at the "click on enter username". where is it? i cant find it. im so confused

**Comment by eKeiran** [comment]
Hi @Domxoxo 
There was a bug in the .rmskin and "click on enter username" wasn't visible. 
I have fixed it now and uploaded the updated .rmskin on deviantART. You can download and install the skin from there or download the .zip from github and place it in your skins folder. You should be seeing the "enter username" now. Sorry for the inconvenience and thank you for noticing!
